name: Cypress e2e
on: [push]

jobs:
  cypress-run-ubuntu:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: Npm Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

    
      - name: Npm Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: http://localhost:4200
          browser: chrome
          record: false
          install: false

      - name: Cypress run on Firefox
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: http://localhost:4200
          browser: firefox
          install: false

  cypress-run-windows:
    runs-on: windows-latest
    needs: cypress-run-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Npm cache
        uses: actions/cache@v2
        id: cache-windows
        with:
          path: |
            ./node_modules
            C:\Users\runneradmin\AppData\Local\Cypress\Cache
          key: ${{ runner.os }}-node-windows-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-windows-

      - name: Npm install
        if: steps.cache-windows.outputs.cache-hit != 'true'
        run: npm install

      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v2
        if: always()
        with:
          config: baseUrl="https://betteroffcalculator.co.uk"
          browser: chrome
          install: false
        env:
          CYPRESS_CACHE_FOLDER: C:\Users\runneradmin\AppData\Local\Cypress\Cache

      - name: Cypress run on Firefox
        uses: cypress-io/github-action@v2
        if: always()
        with:
          start: npm start
          wait-on: http://localhost:4200
          browser: firefox
          install: false
        env:
          CYPRESS_CACHE_FOLDER: C:\Users\runneradmin\AppData\Local\Cypress\Cache

      - name: Cypress run on Edge
        uses: cypress-io/github-action@v2
        if: always()
        with:
          start: npm start
          wait-on: http://localhost:4200
          browser: edge
          install: false
        env:
          CYPRESS_CACHE_FOLDER: C:\Users\runneradmin\AppData\Local\Cypress\Cache


# jobs:
#   cypress-run-chrome:
#     runs-on: ubuntu-16.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Cypress run on Chrome
#         uses: cypress-io/github-action@v2
#         with:
#           start: npm start
#           wait-on: http://localhost:4200
#           browser: chrome
#   cypress-run-firefox:
#     needs: cypress-run-chrome
#     runs-on: ubuntu-latest
#     container:
#       image: cypress/browsers:node12.18.3-chrome87-ff82
#       options: --user 1001
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Cypress run on Firefox
#         uses: cypress-io/github-action@v2
#         with:
#           start: npm start
#           wait-on: http://localhost:4200
#           browser: firefox
#   cypress-run-edge:
#     needs: cypress-run-firefox
#     runs-on: windows-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Cypress run on Edge
#         uses: cypress-io/github-action@v2
#         with:
#           start: npm start
#           wait-on: http://localhost:4200
#           browser: edge
